import { MEMBER_LEVEL } from "./enum";

export enum ErrCode {
	MISS_PARAMETER = 'MISS_PARAMETER',
	DATABASE_ACCESS_ERROR = 'DATABASE_ACCESS_ERROR',
	TOKEN_ERROR = 'TOKEN_ERROR',
	ERROR_PARAMETER = 'ERROR_PARAMETER',
	ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
	INSUFFICENT_PERMISSIONS = 'INSUFFICENT_PERMISSIONS',
	USER_IS_NOT_ACTIVATED = 'USER_IS_NOT_ACTIVATED',
	VERIFY_CODE_ERROR = 'VERIFY_CODE_ERROR',
	ACCOUNT_OR_PASSWORD_ERROR = 'ACCOUNT_OR_PASSWORD_ERROR',
	ACCOUNT_IS_NOT_ACTIVATED = 'ACCOUNT_IS_NOT_ACTIVATED',
	ACCOUNT_IS_LOCKED = 'ACCOUNT_IS_LOCKED',
	UNEXPECTED_ERROR_ARISE = 'UNEXPECTED_ERROR_ARISE',
	SMS_SEND_ERROR = 'SMS_SEND_ERROR',
	CAPTCHA_ERROR = 'CAPTCHA_ERROR',
	SMS_CODE_TOO_FAST = 'SMS_CODE_TOO_FAST',
	TOKEN_EXPIRED = 'TOKEN_EXPIRED',
	BEEN_LOGOUT = 'BEEN_LOGOUT',
	PHONE_ERROR = 'PHONE_ERROR',
	CAPTCHA_TOO_LATE = 'CAPTCHA_TOO_LATE',
	PHONE_EXIST = 'PHONE_EXIST',
	KS_MEMBER_NOT_FOUND = 'KS_MEMBER_NOT_FOUND',
	COUPONBATCH_CANCEL_ISSUED = 'COUPONBATCH_CANCEL_ISSUED',
	COUPONBATCH_CANCEL_CANCELED = 'COUPONBATCH_CANCEL_CANCELED',
	COUPONBATCH_AUTHORIZE_ERROR = 'COUPONBATCH_AUTHORIZE_ERROR',
	COUPONBATCH_ISSUED_ERROR = 'COUPONBATCH_ISSUED_ERROR',
	COUPON_CANCELED_ERROR = 'COUPON_CANCELED_ERROR',
	COUPON_NOT_ISSUED_ERROR = 'COUPON_NOT_ISSUED_ERROR',
	COUPON_USED_ERROR = 'COUPON_USED_ERROR',
	SMS_TOO_LATE = 'SMS_TOO_LATE',
	SHARE_HOLDER_ALREADY_BE_TAKEN = 'SHARE_HOLDER_ALREADY_BE_TAKEN',
	COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
	COUPONBATCH_NOT_FOUND = 'COUPONBATCH_NOT_FOUND',
	MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
	ANNOUNCE_PUBLISH_ERROR = 'ANNOUNCE_PUBLISH_ERROR',
	TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',
	TEAM_ERROR_CONTACT_PERSON = 'TEAM_ERROR_CONTACT_PERSON',
	TEAM_MEMBER_ALREADY_EXISTS = 'TEAM_MEMBER_ALREADY_EXISTS',
	TEAM_ACTIVITY_NOT_FOUND = 'TEAM_ACTIVITY_NOT_FOUND',
	SELECTED_TIME_SECTION_ASSIGNED = 'SELECTED_TIME_SECTION_ASSIGNED',
	RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND',
	MUST_BE_A_APPMEMBER = 'MUST_BE_A_APPMEMBER',
	ANNOUNCEMENT_NOT_FOUND = 'ANNOUNCEMENT_NOT_FOUND',
}
export enum ErrMsg {
	MISS_PARAMETER = '參數不足',
	DATABASE_ACCESS_ERROR = '資料庫連線錯誤',
	TOKEN_ERROR = '權杖(token)錯誤',
	ERROR_PARAMETER = '參數錯誤',
	ITEM_NOT_FOUND = '查無資料(ID可能錯誤)',
	INSUFFICENT_PERMISSIONS = '權限不足',
	USER_IS_NOT_ACTIVATED = '帳號未啟用',
	VERIFY_CODE_ERROR = '驗證碼錯誤',
	ACCOUNT_OR_PASSWORD_ERROR = '帳號或密碼錯誤',
	ACCOUNT_IS_NOT_ACTIVATED = '帳號未啟用',
	ACCOUNT_IS_LOCKED = '帳號已鎖定',
	UNEXPECTED_ERROR_ARISE = '出現意外錯誤',
	SMS_SEND_ERROR = '簡訊驗證碼傳送訊息',
	CAPTCHA_ERROR = '圖形驗證碼產生錯誤',
	SMS_CODE_TOO_FAST = '簡訊驗證碼發送間隔過短',
	TOKEN_EXPIRED = '權杖(token)過期',
	BEEN_LOGOUT = '帳號已登出',
	PHONE_ERROR = '手機號碼錯誤',
	CAPTCHA_TOO_LATE = '圖形驗證碼過期',
	PHONE_EXIST = '手機號碼已存在',
	KS_MEMBER_NOT_FOUND = '找不到國興會員,編號可能有錯',
	COUPONBATCH_CANCEL_ISSUED = '該批次業已發行,無法執行本功能',
	COUPONBATCH_CANCEL_CANCELED = '該批次業已刪除,無法執行本功能',
	COUPONBATCH_AUTHORIZE_ERROR = '優惠券批次發行錯誤',
	COUPONBATCH_ISSUED_ERROR = '優惠券已發行,無法修改',
	COUPON_CANCELED_ERROR = '優惠券已作廢',
	COUPON_NOT_ISSUED_ERROR = '優惠券未發行',
	COUPON_USED_ERROR = '優惠券己被使用',
	SMS_TOO_LATE = '簡訊驗證碼過期',
	SHARE_HOLDER_ALREADY_BE_TAKEN = '股東或眷屬代號已設定給其他會員了',
	COUPON_NOT_FOUND = '查無此優惠券',
	COUPONBATCH_NOT_FOUND = '查無此優惠券批次',
	MEMBER_NOT_FOUND = '查無此會員',
	ANNOUNCE_PUBLISH_ERROR = '公告發佈錯誤',
	TEAM_ERROR_CONTACT_PERSON = '至少需要指定隊長或經理',
	TEAM_MEMBER_ALREADY_EXISTS = '己經是球隊成員了',
	TEAM_NOT_FOUND = '查無此球隊資料',
	TEAM_ACTIVITY_NOT_FOUND = '查物此球隊活動資料',
	SELECTED_TIME_SECTION_ASSIGNED = '選定的時間段已被分配了，請選擇其他時段。',
	RESERVATION_NOT_FOUND = '找不到預約記錄,請檢查預約ID.',
	MUST_BE_A_APPMEMBER = '必須是App會員',
	ANNOUNCEMENT_NOT_FOUND = '查無公告。',
}
export const getErrorMessage = (code: ErrCode): string => {
	const errKey = Object.keys(ErrCode).find((key) => ErrCode[key as keyof typeof ErrCode] === code);
	return errKey ? ErrMsg[errKey as keyof typeof ErrMsg] : '未知錯誤';
};

export enum DtoErrMsg {
	ID_STYLE_ERROR = '不正確的id格式',
	ID_OR_PHONE_AT_LEAST = 'id或手機號碼,請擇一輸入',
	PHONE_STYLE_ERROR = '電話號碼格式錯誤',
	PASSWORD_STYLE_ERROR = '密碼格式錯誤,應包含大小寫字母、數字,長度6-15碼',
	DATE_STYLE_ERROR = '日期格式(YYYY/MM/DD)錯誤',
	TIME_STYLE_ERROR = '時間格式(00:00 - 23:59)錯誤',
	EMAIL_STYLE_ERROR = '電子郵件格式錯誤',
	ARRAY_STYLE_ERROR = '資料必須是陣列格式',
	MISS_BIRTH_MONTH = '生日月份未填',
	ID_ERROR = '代號錯誤',
	UUID_STYLE_ERROR = 'UUID格式錯誤',
	SHARE_HOLDER_ERROR = `membershipType 只能是 ${MEMBER_LEVEL.GENERAL_MEMBER} 或 ${MEMBER_LEVEL.DEPENDENTS}.`,
	MISS_FREQUENCY = '當發行為自動時,參數 frequency 是比填的.'
}
// export const errorMsg = (code:ErrCode) => {
// 	let errKey = '';
// 	Object.keys(ErrCode).some((key) => {
// 		if (ErrCode[key] === code) {
// 			errKey = key;
// 			return true;
// 		}
// 	});
// 	console.log("errorMsg:", errKey);
// 	return ErrMsg[errKey];	
// } 